version: '3.8'
services:
  gateway:
    build: ../server/gateway
    ports:
      - "8000:8000"
    restart: unless-stopped
  security:
    build: ../server/security
    ports:
      - "8080:8080"
    restart: unless-stopped
  migration:
    build: ../server/migration
    ports:
      - "8090:8090"
    restart: unless-stopped
  config:
    build: ../server/config
    ports:
      - "8070:8070"
    restart: unless-stopped
  upgrade:
    build: ../server/upgrade
    ports:
      - "8060:8060"
    restart: unless-stopped
  fencing:
    build: ../server/fencing
    ports:
      - "8050:8050"
    restart: unless-stopped
